name: Guthub action Demo
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps: 
      - name: Checkout 
        uses: actions/checkout
      - run: |
          echo "Hello world"
  
